### ISSUE TITLE
file not available

### ISSUE THREAD

**Issue by un-lock-me** [YongfeiYan/Neural-Document-Modeling#1]
Thanks for sharing your code.
Actually, while running this script:
`bash scripts/topic_coherence.sh data/topic-1.topics data/20news-clean/corpus/ data/topic-1.res`
I can not see any topic file in your folders.

**Comment by un-lock-me** [comment]
This file here does not look like the topics `https://github.com/YongfeiYan/Neural-Document-Modeling/blob/master/data/topic-1.topics`.

Could you please explain about this?

**Comment by un-lock-me** [comment]
and which preprocessing step I need to take? I just removed stop words and did not do stemming. Did you prepare the resource data the same way?

I appreciate if you could let me know about this.

**Comment by YongfeiYan** [comment]
Sorry for late response. I'm not notified by email.
Each line of topic-1.topics has top-100 words instead of top-10. The topic coherence is just based on the first 10 words., ignoring other 90 words.
